title: Notehub Manoa
description: Website that lets you share and view previous semester notes for your classes
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
